Mon May 11 00:23:42 2020
Traceback (most recent call last):
  File "D:\kfw_dev\load game.py", line 8, in <module>
    g.play()
  File "D:\kfw_dev\kf_lib\game.py", line 442, in play
    play = self.game_loop()
  File "D:\kfw_dev\kf_lib\game.py", line 230, in game_loop
    brk = choice()
  File "D:\kfw_dev\kf_lib\game.py", line 634, in test
    p.give_money(50)
AttributeError: 'HumanPlayer' object has no attribute 'give_money'
